# golangci-lint configuration file.
# https://golangci-lint.run/usage/configuration/
version: "2"
linters:
  enable:
    - gocyclo
    - revive
  settings:
    revive:
      rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
formatters:
  enable:
    - gofmt
    - goimports
